![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [6]:
my_array = np.arange(10)
print(my_array[-1::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array[2::-1])


[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [9]:
matrix_4 = np.arange(1, 21).reshape(4,5)
print(matrix_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [22]:
import pprint
vista_5 = matrix_4[:2, :2]
pprint.pprint(vista_5)

array([[1, 2],
       [6, 7]])


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
array_6 = matrix_4[::2, ::2]
pprint.pprint(array_6)

array([[ 1,  3,  5],
       [11, 13, 15]])


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [24]:
array_7 = matrix_4[:3, -1::-1]
pprint.pprint(array_7)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

x_masc = x == 'Loro'
print(x_masc)

print(x[x_masc])

['Loro' 'Loro']


In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

print(x[x == 'Loro'])

[ True False False  True False]
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [34]:
array_9 = np.random.rand(20)
print(array_9)

array_9_2 = array_9.reshape(2,5,2)
print(array_9_2)

[0.99662165 0.32008549 0.13018419 0.90692325 0.05062468 0.71259598
 0.02088371 0.24422517 0.26004845 0.33549242 0.57453424 0.39203598
 0.31198735 0.41192612 0.46357963 0.4489829  0.27967428 0.38439537
 0.92681522 0.65448196]
[[[0.99662165 0.32008549]
  [0.13018419 0.90692325]
  [0.05062468 0.71259598]
  [0.02088371 0.24422517]
  [0.26004845 0.33549242]]

 [[0.57453424 0.39203598]
  [0.31198735 0.41192612]
  [0.46357963 0.4489829 ]
  [0.27967428 0.38439537]
  [0.92681522 0.65448196]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [39]:
array_10 = np.zeros(10)
print(array_10)
print(array_10.dtype)
print(array_10.nbytes)

array_10[3] = 1
print(array_10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
80
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [41]:
array_11 = np.arange(10, 50)
print(array_11)
array_11_2 = array_11[::-1]
print(array_11_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [48]:
# Yo no he entendido de manera en que devuelva 
# el mismo array sin 0s. 
# He entendido que devuelve un array de índices de
# los elementos diferentes a 0 
def quitar_0s(array):
    return array[array != 0]

def indices_no0s(array):
    return np.where(array != 0)

In [55]:
array_12 = np.array([1,2,0,0,4,0])
print(array_12)

# Quito los 0s del array
print(quitar_0s(array_12))

# Devuelvo índices de los elementos que no son 0
array_12 = np.array([1,2,0,0,4,0])
print(indices_no0s(array_12))

[1 2 0 0 4 0]
[1 2 4]
(array([0, 1, 4]),)


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [57]:
matrix_13 = np.random.rand(10,10)
print(matrix_13)

print(matrix_13.min())
print(matrix_13.max())

[[0.43515907 0.62552137 0.27912182 0.94211994 0.23899893 0.7495606
  0.89992516 0.42322213 0.36287107 0.30269777]
 [0.39373677 0.30564369 0.83534772 0.48975891 0.87230644 0.77808332
  0.04752117 0.04473878 0.58768745 0.42519289]
 [0.73370891 0.86437787 0.89799502 0.20083505 0.45080196 0.21510598
  0.14955494 0.02339229 0.79038555 0.94256245]
 [0.21198839 0.78808889 0.43548533 0.5002834  0.67688946 0.27637623
  0.86657427 0.62917781 0.12188703 0.74133923]
 [0.24938088 0.51710914 0.42524879 0.5162476  0.55867406 0.98388738
  0.78507345 0.59713223 0.72605711 0.77498895]
 [0.99578983 0.03723076 0.67512823 0.17914304 0.75595144 0.14368444
  0.96870977 0.12159876 0.8472524  0.298194  ]
 [0.02488677 0.89219298 0.53830174 0.89364669 0.33740987 0.38058386
  0.70796075 0.48970636 0.27098639 0.28712102]
 [0.55311307 0.79938815 0.26664351 0.81468927 0.78582691 0.80272922
  0.64035759 0.22921082 0.97397694 0.04923743]
 [0.78525822 0.16786123 0.64683272 0.0041366  0.59703979 0.06260327
  0.10520697 

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [60]:
vector_14 = np.random.rand(30)
print(vector_14)

media = np.mean(vector_14)
print(media)


[0.97015705 0.0888324  0.77690138 0.73403819 0.89023142 0.44443012
 0.41822447 0.22026034 0.01118777 0.55760813 0.64410972 0.28075747
 0.38104185 0.52770557 0.78705947 0.14641259 0.72010877 0.10370355
 0.18391426 0.7946005  0.35101949 0.72435858 0.04390342 0.12840386
 0.70097426 0.4924634  0.80110088 0.71887408 0.37626871 0.94815944]
0.49889370482700257


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [10]:
import random
n = int(random.randint(2,6)) # Matrices cuadradas de 2 a 6 dimensiones

array_15 = np.zeros((n,n))
array_15[0, :] = 1
array_15[-1, :] = 1
array_15[:, 0] = 1
array_15[:, -1] = 1
print(array_15)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [15]:
array_16 = np.full((8,8), 1)
array_16[::2, ::2] = 0
array_16[-1::-2, -1::-2] = 0
print(array_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [14]:
array_17 = np.array([[0, 1],
                     [1, 0]])
array_17_2 = np.tile(array_17, (4,4))
print(array_17_2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
np.random.seed(42)
array_18 = np.random.rand(5,5)
print(array_18)

media = array_18.mean()
desv = array_18.std()
norm = (array_18 - media) / desv
print(norm)




[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]
[[-0.23709911  1.82467557  1.04200929  0.56488331 -1.01905371]
 [-1.01914002 -1.36950322  1.52216525  0.57367372  0.95640937]
 [-1.5036896   1.89336468  1.40145369 -0.81751722 -0.92670866]
 [-0.92105645 -0.48865218  0.30043311 -0.03168212 -0.5352181 ]
 [ 0.61209803 -1.07818578 -0.53194206 -0.26636415  0.05464636]]
[[-0.23709911  1.82467557  1.04200929  0.56488331 -1.01905371]
 [-1.01914002 -1.36950322  1.52216525  0.57367372  0.95640937]
 [-1.5036896   1.89336468  1.40145369 -0.81751722 -0.92670866]
 [-0.92105645 -0.48865218  0.30043311 -0.03168212 -0.5352181 ]
 [ 0.61209803 -1.07818578 -0.53194206 -0.26636415  0.05464636]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
array_19 = np.arange(11)
print(array_19)

array_19_2 = np.where((array_19 >= 3) & (array_19 <= 8), -1, array_19)
print(array_19_2)

# Negar matemáticamente es buscar el número opuesto, en este caso cambiar el signo a un número
array_19_3 = np.where((array_19 >= 3) & (array_19 <= 8), -array_19, array_19)
print(array_19_3)

print(array_19)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
