![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [3]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(my_array[::-2])

[9 7 5 3 1]


In [5]:
print(my_array[my_array % 2 == 1][::-1])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(my_array[2::-1])

[2 1 0]


In [10]:
print(sorted(my_array[:3],reverse=True))

[np.int64(2), np.int64(1), np.int64(0)]


In [11]:
np.take(my_array, [2,1,0])

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [12]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [13]:
my_matrix.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [14]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [16]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [17]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [19]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [21]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [22]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [23]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [24]:
x == "Loro"

array([ True, False, False,  True, False])

In [25]:
x[x == "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [26]:
print(np.where(x == "Loro")[0])

[0 3]


In [27]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

In [28]:
# np.where(x == "Loro", x, np.nan)

## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [29]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [30]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


In [31]:
x = np.arange(20).reshape(10,2)
print(x)
m1,m2 = np.vsplit(x,[5])
print()
print(m1)
print()
print(m2)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [32]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [33]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

8
80


In [34]:
print(x.dtype)

float64


In [35]:
x = np.full(10, 0)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [36]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

8
80


In [37]:
print(x.dtype)

int64


In [38]:
x = np.full(10, 0, dtype=np.int8)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [39]:
print(x.itemsize) # bytes por elemento 1 byte = 8 bits
print(x.nbytes)

1
10


In [40]:
2 ** 8

256

In [41]:
# 101010110

In [42]:
2**0 + 2**1 + 2**2 + 2**3 + 2**4 + 2**5 + 2**6 + 2**7

255

In [43]:
[-128,127]

[-128, 127]

In [44]:
x[3] = 1
# x[3] = 127
# x[3] = 128
print(x)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [45]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [46]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [47]:
ejer_12 = np.array([1,2,0,0,4,0])
print(ejer_12)

[1 2 0 0 4 0]


In [48]:
type(np.where(ejer_12 != 0)[0])

numpy.ndarray

In [49]:
ejer_12[np.where(ejer_12 != 0)]

array([1, 2, 4])

In [50]:
def f_ejer_12(array_1d):
    return np.where(array_1d != 0)[0]

In [51]:
arr_ej = np.array([3,7,2,0,5,0])
print(f_ejer_12(arr_ej))
print(arr_ej[f_ejer_12(arr_ej)])

[0 1 2 4]
[3 7 2 5]


In [52]:
np.nonzero(ejer_12)[0]

array([0, 1, 4])

In [53]:
np.argwhere(ejer_12)

array([[0],
       [1],
       [4]])

In [54]:
np.argwhere(ejer_12).reshape(len(np.argwhere(ejer_12)))

array([0, 1, 4])

In [55]:
np.hstack(np.argwhere(ejer_12))

array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [56]:
x = np.random.randint(100, size=(1000,1000))
print(x)
print("Minimo", np.min(x), x.min())
print("Máximo", np.max(x), x.max())
print("Sumatorio", np.sum(x), x.sum())
print("Media", np.mean(x), x.mean())
print("Mediana", np.median(x))

[[32 69 23 ... 74 12 15]
 [34 78 59 ... 94 22  5]
 [62 69  7 ... 55 50 76]
 ...
 [10 95 43 ...  7 77 44]
 [16 73 40 ... 89 88 66]
 [71 53 72 ... 17 34 89]]
Minimo 0 0
Máximo 99 99
Sumatorio 49548877 49548877
Media 49.548877 49.548877
Mediana 50.0


In [57]:
# ej = np.array([1000, 1000, 1100, 1100, 9000])
# print(ej.mean())
# print(np.median(ej))

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [58]:
x = np.random.random(30)
print(x)
print(x.mean())

[0.94213705 0.17482073 0.1533987  0.23090867 0.41172247 0.80687637
 0.87437519 0.52130995 0.22945007 0.74061922 0.46693307 0.38771983
 0.78091638 0.87601544 0.40784537 0.65458609 0.88579633 0.22603848
 0.59509956 0.3420281  0.40488959 0.46841379 0.75629226 0.79935771
 0.30042064 0.58596713 0.75957318 0.07489513 0.66085432 0.32165292]
0.5280304574422684


In [59]:
print(x.sum()/len(x))

0.5280304574422684


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [60]:
ejer_15 = np.full((10,10), 1)
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [61]:
ejer_15[1:-1, 1:-1] = 0
print(ejer_15)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [62]:
def f_ejer_15(tamaño):
    matrix = np.full(tamaño, 1)
    matrix[1:-1, 1:-1] = 0
    return matrix

In [63]:
print(f_ejer_15((3,3)))

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [64]:
print(f_ejer_15((8,8)))

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [65]:
print(f_ejer_15((2,2)))

[[1 1]
 [1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [66]:
x = np.zeros((8,8), dtype=np.int16)
print(x)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [67]:
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [68]:
a = np.array([[0,1],
              [1,0]])
print(a)

[[0 1]
 [1 0]]


In [69]:
x = np.tile(a, (3,3))
print(x)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [70]:
x = np.random.randint(1,20, (5,5))
print(x)

[[15  4 10 11 10]
 [18  6 19  7 13]
 [13  2  3  3  3]
 [ 7  3  5 13  1]
 [16  4  2  3 14]]


In [71]:
np.mean(x)

np.float64(8.2)

In [72]:
(x - np.mean(x)) / np.std(x) 

array([[ 1.23820697, -0.76477489,  0.32776067,  0.50984993,  0.32776067],
       [ 1.78447475, -0.40059637,  1.96656401, -0.21850711,  0.87402845],
       [ 0.87402845, -1.12895341, -0.94686415, -0.94686415, -0.94686415],
       [-0.21850711, -0.94686415, -0.58268563,  0.87402845, -1.31104267],
       [ 1.42029623, -0.76477489, -1.12895341, -0.94686415,  1.05611771]])

In [73]:
np.mean((x - np.mean(x)) / np.std(x)) 

np.float64(1.4210854715202004e-16)

In [74]:
np.std((x - np.mean(x)) / np.std(x)) 

np.float64(1.0)

## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [75]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [76]:
y = x.copy()
y[(y >= 3) & (y <= 8)] = -1
print(y)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [77]:
z = x.copy()
z[(z >= 3) & (z <= 8)] *= -1
print(z)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [78]:
contador = 0 
contador = contador + 1
contador

1

In [79]:
contador = 0 
contador += 1
contador

1

In [80]:
contador = 1 
contador *= 10
contador

10

In [81]:
n = 0
for i in range(5):
    # n = n + 1
    n += 1
    print(n)

1
2
3
4
5


In [82]:
n = 1
for i in range(5):
    # n = n * 2
    n *= 2
    print(n)

2
4
8
16
32
