![imagen](./img/ejercicios.png)

In [2]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden, usando numpy.

In [6]:
my_array = np.arange(10)
print(my_array[-1::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array[2::-1])


[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [3]:
matrix_4 = np.arange(1, 21).reshape(4,5)
print(matrix_4)

print(np.flip(matrix_4))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [5]:
import pprint
vista_5 = matrix_4[:2, :2]
pprint.pprint(vista_5)

array([[1, 2],
       [6, 7]])


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [ ]:
array_6 = matrix_4[::2, ::2]
pprint.pprint(array_6)

array([[ 1,  3,  5],
       [11, 13, 15]])


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [ ]:
array_7 = matrix_4[:3, ::-1]
pprint.pprint(array_7)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [ ]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

x_masc = x == 'Loro'
print(x_masc)

print(x[x_masc])

['Loro' 'Loro']


In [8]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

print(x[x == 'Loro'])

['Loro' 'Loro']


In [9]:
index = np.where(x == 'Loro')
print(x[index])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [10]:
array_9 = np.random.rand(20)
array_9 = np.arange(20)
print(array_9)

array_9_2 = array_9.reshape(2,5,2)
print(array_9_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [11]:
array_10 = np.zeros(10, dtype = int)
print(array_10)
print(array_10.dtype)
print(array_10.nbytes)

array_10[3] = 1
print(array_10)

[0 0 0 0 0 0 0 0 0 0]
int64
80
[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [12]:
array_11 = np.arange(10, 50)
print(array_11)
array_11_2 = array_11[::-1]
print(array_11_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [13]:
print(np.flip(np.arange(10,50)))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [1, 2 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [15]:
# Yo no he entendido de manera en que devuelva 
# el mismo array sin 0s. 
# He entendido que devuelve un array de índices de
# los elementos diferentes a 0 
def quitar_0s(array):
    return array[array != 0]

def indices_no0s(array):
    return np.where(array != 0)

In [16]:
array_12 = np.array([1,2,0,0,4,0])
print(array_12)

# Quito los 0s del array
print(quitar_0s(array_12))

# Devuelvo índices de los elementos que no son 0
array_12 = np.array([1,2,0,0,4,0])
print(indices_no0s(array_12))

[1 2 0 0 4 0]
[1 2 4]
(array([0, 1, 4]),)


## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [18]:
matrix_13 = np.random.rand(10,10)
print(matrix_13)

print(matrix_13.min())
print(np.min(matrix_13))

print(matrix_13.max())
print(np.max(matrix_13))

[[7.65993320e-01 5.34776407e-01 9.05819409e-01 2.61951972e-01
  1.19056373e-01 7.03263068e-01 8.17860985e-01 8.07968431e-01
  8.14468108e-01 6.55801292e-01]
 [9.20732253e-01 5.77545141e-01 1.41075436e-01 7.77203335e-01
  9.12168005e-05 4.60534282e-01 8.72204171e-01 9.21489532e-01
  9.51231623e-01 8.28871811e-01]
 [7.04925468e-01 8.66689922e-01 5.98778145e-01 2.24539982e-02
  3.94974232e-01 1.17430375e-01 2.48702139e-01 8.33829330e-01
  9.70644982e-02 5.59539308e-01]
 [6.82306841e-01 4.45387624e-01 5.18631837e-01 3.02849874e-01
  9.65050936e-02 1.95424250e-01 3.63094262e-01 6.16655183e-01
  5.94410632e-02 6.15306211e-01]
 [4.59181268e-01 3.98669270e-01 6.84999027e-01 6.07026277e-01
  4.84419501e-01 4.18792209e-01 8.72864678e-01 4.94649574e-01
  8.18601112e-01 8.78845894e-03]
 [3.88261447e-01 2.20853631e-01 3.54527773e-01 7.55481561e-01
  5.14292104e-01 8.04191437e-01 7.60961467e-01 6.87060243e-01
  3.02707381e-01 9.65277514e-01]
 [2.53771088e-01 5.20615938e-02 8.92997256e-01 9.10212327e

## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [19]:
vector_14 = np.random.rand(30)
print(vector_14)

media = np.mean(vector_14)
print(media)


print('Media: %.4f' % (np.mean(vector_14)))

[0.71091647 0.92505408 0.50678543 0.37265011 0.85327729 0.22691199
 0.29275548 0.86516994 0.91700173 0.89737047 0.97886965 0.32451415
 0.68361784 0.22352929 0.07528357 0.24773874 0.57580518 0.33579058
 0.03759762 0.47325912 0.33092387 0.08972531 0.25187933 0.00149458
 0.45907516 0.89682908 0.08012406 0.56570173 0.83447838 0.38178085]
0.4805303686262487
Media: 0.4805


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [29]:
import random
n = int(random.randint(2,6)) # Matrices cuadradas de 2 a 6 dimensiones

array_15 = np.zeros((n,n), dtype = int)
array_15[0, :] = 1
array_15[-1, :] = 1
array_15[:, 0] = 1
array_15[:, -1] = 1
print(array_15)

[[1 1]
 [1 1]]


In [36]:
import random
n = int(random.randint(2,6)) # Matrices cuadradas de 2 a 6 dimensiones

array_15 = np.ones((n,n), dtype = int)
array_15[1:-1, 1:-1] = 0
print(array_15)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
array_16 = np.full((8,8), 1) # np.ones((8,8), dtype = int)
array_16[::2, ::2] = 0
array_16[-1::-2, -1::-2] = 0
print(array_16)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [14]:
array_17 = np.array([[0, 1],
                     [1, 0]])
array_17_2 = np.tile(array_17, (4,4))
print(array_17_2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [ ]:
np.random.seed(42)
array_18 = np.random.rand(5,5)
print(array_18)

media = array_18.mean()
desv = array_18.std()
norm = (array_18 - media) / desv
print(norm)




[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]
[[-0.23709911  1.82467557  1.04200929  0.56488331 -1.01905371]
 [-1.01914002 -1.36950322  1.52216525  0.57367372  0.95640937]
 [-1.5036896   1.89336468  1.40145369 -0.81751722 -0.92670866]
 [-0.92105645 -0.48865218  0.30043311 -0.03168212 -0.5352181 ]
 [ 0.61209803 -1.07818578 -0.53194206 -0.26636415  0.05464636]]
[[-0.23709911  1.82467557  1.04200929  0.56488331 -1.01905371]
 [-1.01914002 -1.36950322  1.52216525  0.57367372  0.95640937]
 [-1.5036896   1.89336468  1.40145369 -0.81751722 -0.92670866]
 [-0.92105645 -0.48865218  0.30043311 -0.03168212 -0.5352181 ]
 [ 0.61209803 -1.07818578 -0.53194206 -0.26636415  0.05464636]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
array_19 = np.arange(11)
print(array_19)

array_19_2 = np.where((array_19 >= 3) & (array_19 <= 8), -1, array_19)
print(array_19_2)

# Negar matemáticamente es buscar el número opuesto, en este caso cambiar el signo a un número
array_19_3 = np.where((array_19 >= 3) & (array_19 <= 8), -array_19, array_19)
print(array_19_3)

print(array_19)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
